version: '3.8'

services:
  web:
    build: .
    command: python menu/manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=menu
    ports:
      - 8888:5432

volumes:
  postgres_data: