# Generated by Django 4.0.4 on 2022-05-30 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='positions/', verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('proteins', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Proteins')),
                ('fats', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Fats')),
                ('carbohydrates', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Carbohydrates')),
                ('calories', models.PositiveSmallIntegerField(verbose_name='Calories')),
                ('allergens', models.ManyToManyField(blank=True, related_name='product_allergens', to='position.allergen', verbose_name='Allergens')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='position.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ('name',),
            },
        ),
    ]
